### PR TITLE
Introduce shellcheck in ci

### PR DESCRIPTION
**Pull request by rozuur**
Partial fix for #20

### CODE REVIEW

**Comment by 1egoman** [comment]
CI should run within Pull requests now, and since there aren't any secrets in CI I don't think it's that big a deal for them to be on. Here's  the build: https://circleci.com/gh/1egoman/biome/141

**Comment by 1egoman** [comment]
I'm fine with merging this, is this PR something that you'd like to continue working on or should I merge it now?

**Comment by rozuur** [comment]
Can you merge this now? I will revisit this next week to fix other concerns

**Comment by 1egoman** [comment]
Great, thanks for the contribution!

**Pull request merged**
