### PR TITLE
add project subshell prompt for bash

### PR DESCRIPTION
**Pull request by joesavage**
Implements the functionality of 1egoman/biome#13 for bash.

### CODE REVIEW

**Comment by 1egoman** [comment]
@joesavage That's a really clever solution to prepend to the prompt! However, it breaks if I define `PROMPT_COMMAND="echo 'this is the prompt command in by bashrc'"
` in my `.bashrc`. 

image

If you don't have a quick fix for this I'll merge what you've done and I'll think about it some more. Again, thanks a lot!

**Comment by joesavage** [comment]
Hmm, that is a pain, and isn't something I had considered. Ultimately, it looks like any variable we set could be overwritten in the `.bashrc`, and I'm not sure a general solution exists to solve this. I'll have a think about it over the next few days though, perhaps there is some way around.

**Comment by 1egoman** [comment]
@joesavage Ok. I'll keep it open for now in case you think of anything. If you want the hacktoberfest credit, ping me before the end of October and I'll merge it in for you.

Thanks again for the help! 👏

**Comment by joesavage** [comment]
Happy to help! Since this requires shell-specific code in any case, I just asked the #bash channel on freenode what they thought about this issue, and it doesn't look like there's particularly elegant way to do this.

There is, however, a method of getting around this problem of the `.bash_profile` overwriting variables that we want to keep around. If appending a few lines to the user's `.bash_profile` that don't impact non-biome shells is acceptable, I have a replacement patch that I can force push over the previous commit which solves this problem quite nicely.

**Comment by 1egoman** [comment]
@joesavage Yea, I think that'd be acceptable, as long as it's clear to the user what is happening. And if patching the shell profile fails, then biome should fall back to what's being done currently (ie, the magic with `PROMPT_COMMAND`)

**Comment by joesavage** [comment]
For now, this patch simply inserts the code into the `.bash_profile` file if the user is using bash and the file already exists when the `~/.biome` folder is created. In future though, it might be nice to ask the user whether they want this and to store their preference (currently, without a way to carry state across shell script invocations, I decided that asking the user each time they run `biome use` would be excessive).

**Comment by 1egoman** [comment]
@joesavage I like where this is going. I did find one small bug, though.

In a fresh shell, with a clean `.bash_profile` and no `~/.biome`, if a user runs any biome command, the shell snippet is injected as expected. But, if they run `biome use`, they get dropped into a shell like this: `(project) (project) $`. The reason why is that you're checking for the value of `BIOME_SHELL_INIT_CFG` in the parent shell, and since it doesn't have the latest `.bash_profile` changes, the subshell inherits a stale state. 

I think an easy way to fix this would be to tell the user after the code is injected into `~/.bash_profile` to either restart their shell or `source ~/.bash_profile`.

Other than that, this looks great. It may be worth writing a test for the `~/.bash_profile` code injection but I'll leave it up to you.

**Comment by joesavage** [comment]
Oops, quite right! Sorry about that, I'm not quite sure how I didn't notice it. I've added another commit to address this issue, only setting `PS1` in the `PROMPT_COMMAND` if `BIOME_SHELL_INIT_CFG` is not set.

**Comment by 1egoman** [comment]
Looks great! Thanks a lot for working on this!

Issue to write tests: #22

**Pull request merged**
