### PR TITLE
Hidden Biomefile

### PR DESCRIPTION
**Pull request by Thomasvdam**
I think this should do the trick. I'm by no means a bash master so please point out any mistakes or style issues and I'll be glad to fix them.

I'm also not familiar with testing bash scripts at all so I wrote those on good faith pretty much. If you could provide some pointers where I can learn about setting up a testing environment I can fix them should they be incorrect.

### CODE REVIEW

**Comment by Thomasvdam** [comment]
Obviously I messed up somewhere. 😭  I'll try looking a little more into the testing, seeing how the CI did it helped a bit.

**Comment by Thomasvdam** [comment]
Figured it out, I'm just really dumb. Since the init now also asks for a hidden or visible `Biomefile` the input wouldn't compute. >_>

**Comment by 1egoman** [comment]
@Thomasvdam I'm going to review this tomorrow, but first impressions look good!

**Comment by 1egoman** [comment]
**Some initial feedback:**

- I think letting a user set whether they want a `.Biomefile` or a `Biomefile` on init may be confusing to new users. I think it might make sense to either bury this under a flag (ie,  a use could run biome init --hidden) or somehow make the process more obvious.

- I know I said that we'd want to be clear about the fact that there can be a `Biomefile` or a `.Biomefile`, but I think mentioning it everywhere gets a little repetitive. Since this is a more power-user feature I think just mentioning it in one spot (possibly around where it's functionality is most obvious in `biome init`).

- Could you add a test similar to [this](https://github.com/1egoman/biome/blob/master/test/command.bats#L227-L235) that asserts `.Biomefile`s work?

Other than those small points, I really like what you did here! Great job!

**Quick note about testing:**

Also, I think at this point you've figured this out, but I use [bats](https://github.com/sstephenson/bats) to test this project. I create a "fake" environment to run the tests in within 'test/workspace` (I spoof `$HOME` and a few other variables to do this). It seems to work great, though there's probably a much better way to go about it.

**Comment by 1egoman** [comment]
@Thomasvdam

**Comment by Thomasvdam** [comment]
Thanks for the feedback! Good point about the power users, hadn't really considered that. I hope I'll be able to get round to fixing those things up tomorrow evening. :)

**Comment by Thomasvdam** [comment]
I rebased my changes onto your work, which is why this request looks a little odd now.

Anyway, I incorporated your feedback and toned down the mentioning of `.Biomefile`. I also moved the functionality to a flag and modified the tests accordingly. Also added tests for the nested `.Biomefile` as you suggested. If there's anything else you'd like to see let me know. :)

**Comment by 1egoman** [comment]
This looks great. Thanks again for taking on this issue!

**Pull request merged**
